name: Publish Python pk

on:
  release:
    types: [published]

jobs:
  build-and-publish:
    runs-on: windows-latest
    permissions:
      id-token: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        version: "0.7.2"

    - name: Set up Python
      run: |
        uv python install 3.11

    - name: Extract version from tag
      run: |
        # 从标签中提取版本号（去除可能的 'v' 前缀）
        $tag = "${{ github.event.release.tag_name }}"
        # 如果标签以 'v' 开头，则去除它
        if ($tag.StartsWith('v')) {
          $version = $tag.Substring(1)
        } else {
          $version = $tag
        }
        echo "version=$version" | Out-File -FilePath $env:GITHUB_ENV -Append

    - name: Set package version
      run: |
        # 使用 uv 设置版本号
        uv version $env:VERSION

    - name: Build package
      run: |
        uv build
        Get-ChildItem dist

    - name: Publish to PyPI
      run: uv publish
      env:
        UV_PUBLISH_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
